### ISSUE TITLE
Example submission: Mixing templating and markdown.

### ISSUE THREAD

**Issue by andreas-kupries** [tclssg/tclssg#39]
Tested a bit how markdown and templating mix, and also access to page variables from templating.
First a small input/templates/shortcuts.tcl file

```
    proc var {name} {
        global currentPageId
        return [get-page-variable $currentPageId $name "(**Not Found**: $name)"]
    }
    proc root {} {
        global currentPageId
        return [get-page-data $currentPageId rootDirPath]
    }
```

I made that after figuring out that I was able to access page variables after <%interp-source common.tcl%> into the page. I simply wanted shorter command names, and had no need for a default. Something like `<%$ foo %>` might be even nicer, especially if the spaces can be omitted, i.e. `<%$foo%>`

The test page was

```
    {
        title {Testing stuff}
        hideSidebarNote 1
        site:foo local-foo
        site:core:link  http://core.tcl.tk
        site:core:label {Tcl/Tk}
        site:tcllib     {[Tcllib](http://core.tcl.tk/tcllib)}
    }
    <% interp-source shortcuts.tcl %>

    Local Variable  = <%!var site:foo%>

    Global Variable = <%!var site:fog%>

    Missing Variable = <%! var unknown %>

    Root = <%! root %>

    Link to [<%! var site:core:label %>](<%! var site:core:link %>)

    Link to <%!var site:tcllib%>
```

With that it became clear that markdown formatting in the page variables is properly processed when generating the final page.

I deduce that per-page templating is applied first, and then the result is run through the markdown processor (with possibly some other steps between).

I used the "site:" prefix for all my variables to keep out of tclssg's way. 
I hope that you are willing to bless this or some other prefix as reserved for users, with tclssg never using that namespace.

This now allows me to centralize the information about the links I use in my site, and if any break I edit only this config to fix things up. Also a nice place to store smaller common text blocks. Maybe even extendable into something which can read common text-blocks from other files (neither processed themselves directly, nor copied to the site).

**Comment by dbohdan** [comment]
Interesting approach, and it could work even better if you could source `shortcuts.tcl` automatically (https://github.com/dbohdan/tclssg/issues/34). Would you mind making this a wiki page? 

As for

>I deduce that per-page templating is applied first, and then the result is run through the markdown processor (with possibly some other steps between).

that is incorrect. The process is roughly like this:

1. The website config is loaded and processed.
2. Page variables are extracted from the page's frontmatter and put into the in-memory SQLite DB. It should be emphasized that they are not normal Tcl variables but rather row in a DB table.
3. Macros are expanded in the Markdown content (if enabled).
4. Markdown is converted to HTML.
5. The article template is applied.
6. Document template is applied.

(I'll copy the above list the wiki.)

If you are interested in understanding how Tclssg processes content in more detail and don't want to wait until I write it up you can check out the procs `compile-website` and `generate-html-file` in `ssg.tcl`. I've tried to comment the source of `compile-website` extensively and FWIW the comments helped me after some time away from the code.

Because page variables are not Tcl variables I have doubts about introducing something like `<%$ varName %>`. Perhaps "page settings" should be use exclusively instead. What do you think?

**Comment by dbohdan** [comment]
I've made a branch where the term "setting" is used exclusively in the code and in the README, though not in the templates yet: https://github.com/dbohdan/tclssg/tree/variable-to-setting.

**Comment by dbohdan** [comment]
Pull request to comment on: https://github.com/dbohdan/tclssg/pull/41.

**Comment by andreas-kupries** [comment]
- Working better on auto-load of the shortcuts -- Agreed.
      - Wiki page for it - Sure, will do.
   - Thanks for the correction of my deductions.
      - From your set of steps it looks we have 3 concepts here, namely
         - Macros, Tcl based
         - Markdown
         - Templating, article and document.

        I believe I confused the macros with templating because that was the section in the README where I found them described. Now the question is what is templating then ? CSS ?
        Side q: Is step 2, extraction of the page settings done for __all__ pages before going to step 3 ? Or are the steps done for a single page before going to the next ? It makes a differences in a page P able to access the settings of a different page Q, or not.

Yes, I believe I will have a more detailed look at the code. Comments are always good, yes. Splitting  parts of the code off into their own packages will help too, after a while. The core Critcl 3.x is for example about 150K of Tcl code. In the slice-dice branch of the repo I split 16 packages off that, each smaller and easier to understand.

   - "Page settings" is a good term. Should reduce confusion between them and template variables.

**Comment by dbohdan** [comment]
>I believe I confused the macros with templating because that was the section in the README where I found them described. Now the question is what is templating then ? CSS ?

Templating in Tclssg is the process of generating static markup files from markup with embedded Tcl code by using a variant of [tmpl_parser](http://wiki.tcl.tk/20363#pagetoc06d3740e) on it and evaluating the resulting code. CSS is applied in the browser and (for now) Tclssg does not touch it at all. Macros in pages are a form of templating except the markup in question in Markdown rather than HTML or XML, i.e., you take Markdown with embedded macros and output Markdown.

>Side q: Is step 2, extraction of the page settings done for all pages before going to step 3 ? Or are the steps done for a single page before going to the next ? It makes a differences in a page P able to access the settings of a different page Q, or not.

Yes. All settings are extracted first so that you can refer to other pages' settings regardless of the actual order in which the pages are processed.

**Comment by dbohdan** [comment]
>"Page settings" is a good term. Should reduce confusion between them and template variables.

All right. I think I will be merging that pull request, then. It will break template code but it should be easy to fix with `s/old/new/g` and instructions will be included in the commit message for what to replace with what. I'll also add a validation error to tell the user to rename `pageVariables` in the config.

**Comment by andreas-kupries** [comment]
On the side q, interesting, and that me wonder what tricks this makes possible. (Nothing concrete really yet in my mind).

**Comment by dbohdan** [comment]
>On the side q, interesting, and that me wonder what tricks this makes possible. (Nothing concrete really yet in my mind).

No tricks, really. It's just that templates can't write to the database and each is processed in a "new" safe interpreter, so page can't influence each other's DB data or state. As a result the order of processing shouldn't matter. I've just realized, however, that that is not entirely accurate because pages could in theory 1) mess with each other's text by calling `mcset`; 2) cache data that they shouldn't (the cache is intended for things that are invariant for files in one directory).

**Comment by andreas-kupries** [comment]
Right. Heh, I was actually only thinking of spying on other page's data, not influencing.

**Comment by dbohdan** [comment]
A similar set of shortcut commands was added in ed1167b802d7d05e4ad3b6c0082922de0391b443 (one difference been proc names that reflect page/website variables having been renamed "settings").

**Comment by dbohdan** [comment]
Could you update this example and put it on the wiki?

**Comment by dbohdan** [comment]
Closing as outdated.  Now you can use a [data file](https://github.com/tclssg/tclssg/wiki/Data-files) or a [preset](https://github.com/tclssg/tclssg/wiki/Presets) to pass common data to pages, and there is a new [template API](https://github.com/tclssg/tclssg/wiki/Template-API).
